"""change models secound time

Revision ID: 2cfec4fb0f5f
Revises: f23db4398984
Create Date: 2024-02-28 11:47:58.776655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cfec4fb0f5f'
down_revision = 'f23db4398984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=sa.FLOAT(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=sa.DateTime(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
