"""update processes model

Revision ID: 6bc4c6781c05
Revises: 33b4c1e02538
Create Date: 2024-03-02 09:07:47.041079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bc4c6781c05'
down_revision = '33b4c1e02538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.alter_column('pid',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('cpu_percent',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('memory_percent',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('cmdline',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('num_threads',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('create_time',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('num_fds',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.alter_column('num_fds',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('create_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('num_threads',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('cmdline',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('memory_percent',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('cpu_percent',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('pid',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
