"""added processes model

Revision ID: 906fa1d2b5dd
Revises: f22bd7a2578a
Create Date: 2024-02-28 00:59:23.736082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906fa1d2b5dd'
down_revision = 'f22bd7a2578a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=False),
    sa.Column('memory_percent', sa.Float(), nullable=False),
    sa.Column('cmdline', sa.Text(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('num_threads', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.Column('num_fds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processes')
    # ### end Alembic commands ###
